### ISSUE TITLE
Update README to point to fulcrumapp's repo?

### ISSUE THREAD

**Issue by kyletolle** [spatialnetworks/fulcrum-ruby#13]
Since the gem points to https://github.com/fulcrumapp/fulcrum-ruby, and that repo is the more current one, should we update the README here to point to that page?

**Comment by colemanm** [comment]
I just added a link. Could we just delete this repo if it's moved? I see a few issues, but can we just post em in the other repo?

**Comment by kyletolle** [comment]
Moving the issues over could be good too.

Not sure how GitHub handles deleted repos. Maybe they let you forward to another link?

If nothing else, we could make another commit that blows away all the code here, and leaves only a link to the new repo in the README.

**Comment by colemanm** [comment]
One option is to do something like this, from when CartoDB project got moved:

https://github.com/Vizzuality/cartodb

**Comment by zhm** [comment]
Done
