### ISSUE TITLE
Why are the coordinates 0,0 rejected by the RecordValidator? 

### ISSUE THREAD

**Issue by stuporglue** [spatialnetworks/fulcrum-ruby#5]
I've got a record with the coordinates 0,0 but the validator explicitly rejects it saying it's not a valid WGS84 coordinate. 

https://github.com/spatialnetworks/fulcrum-ruby/blob/master/lib/fulcrum/validators/record_validator.rb

If I comment out that test the Fulcrum API happily takes my record and places it where I want it. 

What's up? Why won't RecordValidator let me have a record at 0,0?

**Comment by kyletolle** [comment]
The record validator is no longer part of [the project](https://github.com/fulcrumapp/fulcrum-ruby), so this can be closed.
